### PR TITLE
bump scaleway provider

### PR DESCRIPTION
**Pull request by Sh4d1**
This PR uses the new Scaleway Terraform plugin and remove warning with recent TF versions.

Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>

### CODE REVIEW

**Comment by Sh4d1** [comment]
cc @pstadler :smile:

**Comment by pstadler** [comment]
Thanks for your PR. Sorry for this question, but did you test this? Everything working as expected? I'm asking because in the past, Scaleway tended to provide images with some crucial kernel modules disabled.

**Comment by Sh4d1** [comment]
Yep ! Cluster is up and running! Regarding the bootscript -> local boot, it now bases of an upstream kernel, so it's better I guess 😄

**Comment by pstadler** [comment]
Thanks, great PR 🍻

**Pull request merged**
