### PR TITLE
Add Gandi as a DNS service

### PR DESCRIPTION
**Pull request by debovema**
As Gandi is a pretty good DNS provider and they have a brand new API, I suggest to give the possibility to add it in the list of available DNS providers.

I successfully tested this with the following Terraform provider for Gandi 
: https://github.com/tiramiseb/terraform-provider-gandi

### CODE REVIEW

**Comment by pstadler** [comment]
Thanks for your pull request. Please remove the apt_packages variable.

**Comment by pstadler** [comment]
I like the idea of apt_packages being configurable, but this should be applied to all providers and should not be part of this PR.

**Comment by debovema** [comment]
In fact it is applied to all providers (DigitalOcean and Scaleway) and was just a little refactoring before adding Gandi DNS provider.

**Comment by pstadler** [comment]
stalled.

**Pull request closed without merging**
